### ISSUE TITLE
Support fmt.Stringer and error in GetString

### ISSUE THREAD

**Issue by fgm** [icza/dyno#4]
Currently, GetString only works with values able to be converted to actual strings.

However, two very common data types in Go are implementations or `error` and `fmt.Stringer`, which can also be returned as strings. It would be nice to have them also be supported.

I can submit a PR if you think this is a good idea.

**Comment by icza** [comment]
> Primary goal is to easily handle dynamic objects and arrays (and a mixture of these) that are the result of unmarshaling a JSON or YAML text into an interface{} for example.

The result of JSON or YAML unmarshaling will never create values custom types implementing `fmt.Stringer` or `error`, so IMO there is not much benefit of this.

**Comment by fgm** [comment]
Actually it can happen with `json.Unmarshaler` implementations, but indeed they're less common than the basic string.

**Comment by icza** [comment]
Can you give me an example when unmarshaling JSON text with `json.Unmarshal()` into an `interface{}` variable and the result contains something that implements `fmt.Stringer`? I don't know any.

**Comment by fgm** [comment]
Here is an - admittedly very contrived - example, looking like a very simplified version of the reason I suggested this originally https://play.golang.org/p/7ZHq0KFhiXA : in this example, the keys are fmt.Stringer implementations after unmarshalling a JSON string.

**Comment by icza** [comment]
Yes but there you're not unmarshaling into an `interface{}` value but into a value of `justADemo`, a custom type with custom unmarshaling logic.

**Comment by fgm** [comment]
Indeed, that's what I tried to say in my previous message. In the end, I actually reworked the code to avoid this so this issue is no longer important for me: since the primary goal of the project is to help work with plain `interface{}` types, it's really up to you: this example shows a use case, but it's marginally out of your project scope, so...

**Comment by icza** [comment]
I'd like to avoid calling the `String()` method in an opaque way as that may be allocating buffers to generate the `string` representation. This may or may not be what the user want.

**Comment by fgm** [comment]
Makes sense.

**Comment by icza** [comment]
Closing it then.
